title: Ursamajor.technology
description: PowerShell Blog
permalink: /:year/:month/:day/:title/
url: https://ursamajor.technology
github_username: ursaMaj0r

date_format: "%b %-d, %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile

include:
- node_modules