title: Ursamajor.technology
description: PowerShell Blog
permalink: /:slugified_categories/:title/
url: https://ursamajor.technology/
baseurl: 'https://ursamaj0r.github.io/ursamajor.technology/'
github_username: ursaMaj0r

date_format: "%b %-d, %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile

include:
- node_modules