title: Ursamajor.technology
description: PowerShell Blog
permalink: /:year/:month/:day/:title/
url: https://ursamajor.technology
github_username: ursaMaj0r
date_format: "%b %-d, %Y"
google_analytics: G-P1CNC3J644

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-archives
  - jekyll-paginate

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile

include:
- node_modules

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true
theme: minima

# defaults
jekyll_compose:
  default_front_matter:
    drafts:
      id: 000
      author: ursaMaj0r
      views: 0
      image:
      categories:
      tags:
    posts:
      id: 000
      author: ursaMaj0r
      views: 0
      image:
      categories:
      tags:

# plugin configs
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive-categories
  permalinks:
    category: '/category/:name/'

# Pagination Settings
paginate: 5